spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 보통 validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect