spring:
  application:
    name: moimpick
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 20000

server:
  port: 8000