spring:
  application:
    name: moimpick

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 20000